name: Build and Push TimescaleDB Image

on:
  push:
    branches:
      - main  # or your default branch
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggers

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PG_VERSION: "16.6-34"
  PG_MAJOR: "16"
  TIMESCALE_VERSION: "2.17.2"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set custom image tags
        id: tags
        run: |
          MAIN_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-opinionated-${{ env.TIMESCALE_VERSION }}:${{ env.PG_VERSION }}"
          LATEST_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          echo "tags=${MAIN_TAG},${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            PG_VERSION=${{ env.PG_VERSION }}
            PG_MAJOR=${{ env.PG_MAJOR }}
            TIMESCALE_VERSION=${{ env.TIMESCALE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max